### PR TITLE
Support apex domain, handle errors, callback

### PR DESCRIPTION
**Pull request by hugojosefson**
_**PS in advance:** Before checking out this branch, do backup your `.idea` directory you have in this project, because one of my commits deletes the `.idea/*` files, then the next commit adds `.idea` to `.gitignore`. This is because `.idea/*` project files will be different on different computers, in different versions of IDEA or Webstorm._
### Hi Michael!

Great work on this module and figuring out all the details of the CloudFlare API. I really needed this!

I also needed some more things, which was to support updating the A record for the apex domain (no www, just the domain name). And also to be able to make two requests quickly, without the code overwriting its internal state in the meantime, which caused it to do the wrong thing.

When I fixed these things, I needed to make backwards compatible breaks to how it worked, so this means a new [semver](http://semver.org/) major version. I suggest version `2.0.0` to be safe, because people may have different expectations for any breaking changes from `0.x.x` to `1.0.0`. I'll paste the changes from `CHANGES.md` here for your convenience:
- **Feature:** Supports updating A record for the apex domain (no www), using `"@"` as hostname.
- **API Breaking change:** Takes an options object as the single argument.
- **API Breaking change:** Returns a `Promise` which resolves to the actual IP address if the
  request was successful, or rejects with an `Error` if it was not. Requires Node.js 0.12 or later.
- **Fix:** Supports using this module for several requests at the same time, thanks to not keeping
  or mutating internal global state.

I would like to know from you if you are interested in having these changes here in this module (possibly altered if you have opinions on anything), or if you would rather I publish this as a separate module?

Thanks,
Hugo

### CODE REVIEW

**Comment by billiegoose** [comment]
@hugojosefson can you go ahead and publish this as a module on NPM since it doesn't look like the original author is going to?

**Comment by michaelkourlas** [comment]
Realistically, I'm not sure when I'll get around to merging this change, so I think it's best if you fork and publish your own module on npm.

**Comment by hugojosefson** [comment]
That's cool @michaelkourlas, I'll go ahead with a separate npm package. Thanks for the update.

In the meantime @wmhilton, you can do this to use my code directly from my branch on github:

~~`npm install --save 'hugojosefson/node-cloudflare-dynamic-dns#apex-domain'`~~

**Update:** For anyone reading this later, I have published under new name on npm.

Install like this:

``` bash
npm install --save cloudflare-dynamic-dns2
```

**Comment by michaelkourlas** [comment]
Sorry for the delay in getting back to you both -- I'm swamped with coursework at the moment.

**Comment by hugojosefson** [comment]
No problem, @michaelkourlas. Good thing it's open source :)

**Comment by hugojosefson** [comment]
@wmhilton I have published `cloudflare-dynamic-dns2` now: https://www.npmjs.com/package/cloudflare-dynamic-dns2

**Pull request closed without merging**
